using UnityEngine;

/// <summary>
/// Stores auto-generated connect-the-dots contour points for a single shape.
/// Generated by the DotShapeGenerator editor tool from sprite alpha silhouettes
/// or from built-in geometric definitions.
///
/// Complexity levels:
///   0 = Low  (circle, square, fish) → appears in Easy only
///   1 = Medium (cat, bird, turtle)  → appears in Medium only
///   2 = High (giraffe, horse, elephant) → appears in Hard only
/// </summary>
[CreateAssetMenu(fileName = "DotShapeData", menuName = "Kids Learning Game/Dot Shape Data")]
public class DotShapeData : ScriptableObject
{
    public string shapeId;
    public string hebrewName;
    public string animalId;
    public Sprite sourceSprite;
    public Color lineColor = new Color(1f, 0.95f, 0.75f, 0.85f);

    [Header("Complexity (0=Low, 1=Medium, 2=High)")]
    [Range(0, 2)]
    public int complexity;
    public float complexityScore; // raw score for debugging

    [Header("Generated Points (normalized 0–1)")]
    public Vector2[] easyPoints;    // ~8–12 points
    public Vector2[] mediumPoints;  // ~15–20 points
    public Vector2[] hardPoints;    // ~25–30 points

    public Vector2[] GetPoints(int difficulty)
    {
        switch (difficulty)
        {
            case 0: return easyPoints;
            case 1: return mediumPoints;
            case 2: return hardPoints;
            default: return mediumPoints;
        }
    }

    /// <summary>
    /// Returns true if this shape matches the given difficulty.
    /// Easy: Low only. Medium: Medium only. Hard: High only.
    /// </summary>
    public bool IsAllowedForDifficulty(int difficulty)
    {
        return complexity == difficulty;
    }
}
